source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
xcodeproj 'CommonAPIHelpersDemoProject'
workspace '../CommonAPIHelpers'

target :CommonAPIHelpersDemoProject do
	pod 'CommonAPIHelpers/CAHHUD', :path => '../'
	pod 'CommonAPIHelpers/CAHMailController', :path => '../'
	pod 'CommonAPIHelpers/CAHGoogleAnalyticsHelper', :path => '../'
end
